export const SET_HIT = "SET_HIT";
export const SET_MUSIC = "SET_MUSIC";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_ACCOUNT_DETAILS = "SET_ACCOUNT_DETAILS";
export const SET_USER_SIGNATURE = "SET_USER_SIGNATURE";
export const SET_USER_MESSAGE = "SET_USER_MESSAGE";
export const RESET_ACCOOUNT_DETAILS = "RESET_ACCOOUNT_DETAILS";
